SpreadTheGospel/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns
from django.conf.urls import include
from django.conf.urls import url

from django.conf import settings

from django.contrib import admin
admin.autodiscover()

handler500 = "core.views.error500"
handler404 = "core.views.error404"

urlpatterns = patterns("",
    url(r"static/(?P<path>.*)$", "django.views.static.serve", {"document_root" : settings.STATIC_TEMPLATES}),
    url(r"^statics/(?P<path>.*)$", "django.views.static.serve", {"document_root": settings.STATIC_ROOT}, name = "statics"),
    url(r"^admin/menu/menu/move_up/(?P<menu_id>[\d]+)$", "menu.views.menu_move_up"),
    url(r"^admin/menu/menu/move_down/(?P<menu_id>[\d]+)$", "menu.views.menu_move_down"),
    url(r"^admin/", include(admin.site.urls)),
    url(r"^sitemap", include("sitemap.urls")),
    url(r"^robots\.txt$", include("robots.urls")),
    url(r"^grappelli/", include("grappelli.urls")),
    url(r"", include("core.urls")),
)

core/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls.defaults import patterns
from django.conf.urls.defaults import url

from core.feeds import RSS
from core.feeds import Atom

urlpatterns = patterns("core.views",
    url(r"^$", "showPosts"),
    url(r"^feeds/rss/$", RSS(), name = "RSS"),
    url(r"^feeds/atom/$", Atom(), name = "Atom"),
    url(r"^kontakt/sukces/$", "showContactFormSuccessfully"),
    url(r"^kontakt/error/$", "showContactFormUnsuccessfully"),
    url(r"^zglos-bloga/sukces/$", "showRegisterFeedSuccessfully"),
    url(r"^zglos-bloga/error/$", "showRegisterFeedUnsuccessfully"),
    url(r"^zglos-bloga/error-uniq/$", "showRegisterFeedUnsuccessfullyUniq"),
    url(r"^newsletter/$", "showNewsletterForm"),
    url(r"^newsletter/sukces/$", "showRegisterNewsletterSuccessfully"),
    url(r"^newsletter/error/$", "showRegisterNewsletterUnsuccessfully"),
    url(r"^newsletter/(\w{40})$", "confirmNewsletter"),
    url(r"^news/(?P<number>[\w\-_]+)/$", "showPosts"),
    url(r"^szukaj/(?P<page>[\w\-_]+)/$", "showSearchResults", name = "search-results"),
    url(r"^(?P<slug>[\w\-_]+)\-(?P<pk>[\d]+)\.html$", "showSingleNews"),
    url(r"^(?P<subpage>[\w\-_]+)/$", "showSubpage", name = "subpage"),
    url(r"^captcha.png/(?P<url>[\w\-_]+)$", "captchaGenerator", name = "captcha"),
)

core/models.py
# -*- coding: utf-8 -*-

import string
from random import choice

from django.db import models

from core.utils import _slugify
from urlparse import urlparse

from django.core.mail import EmailMessage

from django.core.exceptions import ValidationError

from django.contrib.sitemaps import ping_google

import feedparser

class News(models.Model):
    author = models.CharField(verbose_name = u"Imię i nazwisko/Nick", max_length = 200)
    title = models.CharField(verbose_name = u"Tytuł", max_length = 200)
    text = models.TextField(verbose_name = u"Tekst")
    availability = models.BooleanField(verbose_name = u"Dostępność", default = True)
    url = models.SlugField(verbose_name = u"Adres url", editable = False, max_length = 200)
    href = models.URLField(verbose_name = u"Hiperłącze", editable = False, max_length = 200)
    date = models.DateTimeField(verbose_name = u"Data publikacji")

    class Meta:
        verbose_name = u"News"
        verbose_name_plural = u"newsy"

    def save(self, *args, **kwargs):
        if not self.id:
            super(News, self).save(*args, **kwargs)

        self.url = "%s-%s.html" % (_slugify(self.title), self.id)

        super(News, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return "/%s" % self.url

    def __str__(self):
        return str(self.title)

    def __unicode__(self):
        return unicode(self.title)

class Subpage(models.Model):
    title = models.CharField(verbose_name = u"Tytuł", max_length = 150, unique = True)
    url = models.SlugField(verbose_name = u"URL", max_length = 150, editable = False)
    text = models.TextField(verbose_name = u"Treść", blank = True, null = True)
    modules = ((-1, u"Standardowa"), (0, u"Formularz zgłoszeniowy"), (1, u"Formularz kontaktowy"))
    selectedModule = models.IntegerField(verbose_name = u"Moduł", max_length = 150, choices = modules, default = -1)
    date = models.DateTimeField(verbose_name = u"Data ostatniej edycji", auto_now = True)

    def mod(self):
        return self.modules[self.selectedModule + 1][1]

    mod.allow_tags = True
    mod.short_description = u"Moduł"

    class Meta:
        verbose_name = u"Podstrona"
        verbose_name_plural = u"podstrony"

    def save(self, *args, **kwargs):
        self.url = _slugify(self.title)

        super(Subpage, self).save(*args, **kwargs)

    @models.permalink
    def get_absolute_url(self):
        return (u"subpage", (), {"subpage": self.url})

    def __str__(self):
        return str(self.title)

    def __unicode__(self):
        return unicode(self.title)

class NewsFeed(models.Model):
    author = models.CharField(verbose_name = u"Imię i nazwisko/Nick", max_length = 100)
    email = models.EmailField(verbose_name = u"E-mail")
    source = models.URLField(verbose_name = u"RSS/ATOM", unique = True)
    availability = models.BooleanField(verbose_name = u"Dostępność", default = False)
    sendmail = models.BooleanField(verbose_name = u"Potwierdzenie", default = True)

    class Meta:
        verbose_name = u"Kanał"
        verbose_name_plural = u"kanały"

    def clean(self, *args, **kwargs):
        if not feedparser.parse(self.source).version:
            raise ValidationError(u"Niestandardowy format kanału. Zalecana architektura: RSS 1.0, RSS 2.0 lub ATOM 1.0.")

        super(NewsFeed, self).clean(*args, **kwargs)

    def save(self, *args, **kwargs):
        if self.availability and self.sendmail:
            title = u"pl.python.org/planeta - potwierdzenie akceptacji bloga"
            text = u"Witaj,<br><br>Informujemy, że Twój <a href=\"http://%s\" title=\"%s\">blog</a> został zweryfikowany i dodany do <a href=\"http://pl.python.org/planeta\" title=\"Polska planeta programistów Python\">polskiej planety programistów Python</a>.<br><br>Z poważaniem,<br>Polish Python Coders Group<br><a href=\"mailto:ppcg@pl.python.org\" title=\"ppcg@pl.python.org\">ppcg@pl.python.org</a>" % (urlparse(self.source).hostname, self.author)
            who = u"PPCG Planeta <planeta@pl.python.org>"

            msg = EmailMessage(title, text, who, [self.email])
            msg.content_subtype = "html"
            msg.send()

        super(NewsFeed, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        if self.sendmail:
            title = u"pl.python.org/planeta - potwierdzenie usunięcia bloga"
            text = u"Witaj,<br><br>Informujemy, że Twój <a href=\"http://%s\" title=\"%s\">blog</a> został usunięty z <a href=\"http://pl.python.org/planeta\" title=\"Polska planeta programistów Python\">polskiej planety programistów Python</a>.<br><br>Z poważaniem,<br>Polish Python Coders Group<br><a href=\"mailto:ppcg@pl.python.org\" title=\"ppcg@pl.python.org\">ppcg@pl.python.org</a>" % (urlparse(self.source).hostname, self.author)
            who = u"PPCG Planeta <planeta@pl.python.org>"

            msg = EmailMessage(title, text, who, [self.email])
            msg.content_subtype = "html"
            msg.send()

        super(NewsFeed, self).delete(*args, **kwargs)

    def __str__(self):
        return str(self.author)

    def __unicode__(self):
        return unicode(self.author)

class Subscriber(models.Model):
    email = models.EmailField(verbose_name = u"E-mail", unique = True)
    data = models.DateField(auto_now = True)
    confirmation = models.BooleanField(default = False)
    activation_key = models.CharField(max_length = 40, editable = False)

    def save(self, *args, **kwargs):
        size = 40

        if not self.pk:
            self.activation_key = "".join([choice(string.letters + string.digits) for x in range(size)])

        super(Subscriber, self).save(*args, **kwargs)

    class Meta:
        verbose_name = u"Subskrybent"
        verbose_name_plural = u"subskrybenci"

    def delete(self, *args, **kwargs):
        if self.confirmation:
            title = u"pl.python.org/planeta - potwierdzenie usunięcia z subskrypcji"
            text = u"Witaj,<br><br>Dzięki za dotychczasową subskrypcję.<br><br>Pamiętaj, że w każdej chwili możesz dokonać ponownej rejestracji, wypełniając formularz zgłoszeniowy na stronie <a href=\"http://pl.python.org/planeta\" title=\"Polska planeta programistów Python\">polskiej planety programistów Python</a><br><br>Z poważaniem,<br>Polish Python Coders Group<br><a href=\"mailto:ppcg@pl.python.org\" title=\"ppcg@pl.python.org\">ppcg@pl.python.org</a>"
            who = u"PPCG Planeta <planeta@pl.python.org>"

            msg = EmailMessage(title, text, who, [self.email])
            msg.content_subtype = "html"
            msg.send()

        super(Subscriber, self).delete(*args, **kwargs)

    def __str__(self):
        return str(self.email)

    def __unicode__(self):
        return unicode(self.email)

class JobOffer(models.Model):
    topic_id = models.SmallIntegerField(editable = False, unique = True, default = 0)
    city = models.CharField(verbose_name = u"Miejsce pracy", max_length = 150)
    company = models.CharField(verbose_name = u"Nazwa firmy", max_length = 150)
    title = models.CharField(verbose_name = u"Stanowisko pracy", max_length = 150)
    href = models.URLField(verbose_name = u"Hiperłącze", max_length = 150, blank = True, null = True)
    date = models.DateField(verbose_name = u"Data publikacji")

    def save(self, *args, **kwargs):
        super(JobOffer, self).save(*args, **kwargs)

    class Meta:
        verbose_name = u"Oferta pracy"
        verbose_name_plural = u"oferty pracy"

    def __str__(self):
        return str(self.topic_id)

    def __unicode__(self):
        return unicode(self.topic_id)

core/forms.py
# -*- coding: utf-8 -*-

from django import forms

import feedparser

from django.core.exceptions import ValidationError

def valid_feed(source):
    feed = feedparser.parse(source)

    try:
        if not feed.version:
            raise ValidationError(u"Niestandardowy format kanału. Zalecana architektura: RSS 1.0, RSS 2.0 lub ATOM 1.0.")
    except AttributeError:
        pass

class Newsletter(forms.Form):
    email = forms.EmailField(widget = forms.TextInput(attrs = {"id" : "newsletter_email", "title" : u"Wpisz adres e-mail"}))
    regulation = forms.BooleanField(required = True, initial = False, widget = forms.CheckboxInput(attrs = {"title" : u"Zaakceptuj regulamin"}))

class FeedRegister(forms.Form):
    author = forms.CharField(max_length = 100, widget = forms.TextInput(attrs = {"title" : u"Wpisz imię i nazwisko albo nick"}))
    email = forms.EmailField(widget = forms.TextInput(attrs = {"title" : u"Wpisz adres e-mail"}))
    source = forms.URLField(widget = forms.TextInput(attrs = {"title" : u"Wpisz adres kanału RSS lub ATOM"}), validators = [valid_feed])
    regulation = forms.BooleanField(required = True, initial = False, widget = forms.CheckboxInput(attrs = {"title" : u"Zaakceptuj regulamin", "id" : "id_regulation_sub"}))
    token = forms.CharField(max_length = 8, widget = forms.TextInput(attrs = {"title" : u"Przepisz token z obrazka"}))

class SearchForm(forms.Form):
    fraza = forms.CharField(max_length = 20, widget = forms.TextInput(attrs = {"id" : "search", "title" : "Wpisz szukaną frazę"}))

class ContactForm(forms.Form):
    author = forms.CharField(max_length = 20, widget = forms.TextInput(attrs = {"title" : u"Wpisz imię i nazwisko albo nick"}))
    email = forms.EmailField(widget = forms.TextInput(attrs = {"title" : u"Wpisz adres e-mail"}))
    topic = forms.CharField(max_length = 100, widget = forms.TextInput(attrs = {"title" : u"Wpisz tytuł wiadomości"}))
    message = forms.CharField(widget = forms.Textarea(attrs = {"rows" : 10, "cols" : 60, "title" : u"Wpisz treść wiadomości"}))
    token = forms.CharField(max_length = 8, widget = forms.TextInput(attrs = {"title" : u"Przepisz token z obrazka"}))    

core/templates/base.html
{% spaceless %}
{% load url from future %}
<!DOCTYPE html>
<html lang="pl-PL">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
        <meta name="description" content="{{ config.description }}">
        <meta name="keywords" content="{{ config.keywords }}">
        <meta name="author" content="Katharsis">
        <meta name="robots" content="index, follow">
        <title>{% block title %}{{ config.title }} -{% endblock %} pl.python.org/planeta</title>
        <link rel="shortcut icon" href="{% url 'statics' 'images/favicon.ico' %}">
        <link rel="stylesheet" href="{% url 'statics' 'css/style.css' %}">
        <link rel="alternate" href="/planeta/feeds/atom" type="application/atom+xml" title="Kanał informacyjny PPCG Planeta | pl.python.org/planeta">
    </head>
	<body>
            <header>
                <figure></figure>
                <section id="top">
                <aside id="logo"><h1><a href="/planeta" title="Polska planeta programistów Python">Polska planeta programistów Python</a></h1></aside>
                <nav>
                    <ul>
                        {% for menu in menus %}
                            {% if request.path == menu.url or request.path == menu.url|add:"/" or menu.url != "/planeta" and menu.url in request.path or menu.url == "/planeta" and "/news/" in request.path %}
                                <li class="current"><a href="{{ menu.url }}" title="{{ menu.description }}">{{ menu.name }}</a></li>
                            {% else %}
                                <li><a href="{{ menu.url }}" title="{{ menu.description }}">{{ menu.name }}</a></li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                </nav>
            </section>
            <section id="bottom">
                <form action="{% url 'search-results' 1 %}" method="get">
                    {{ search.fraza }}
                    <input type="submit" title="Szukaj w aktualnościach" value="Szukaj" id="button_szukaj">
                </form>
                {% if site %}
                    <h2 id="update">{{ site }}</h2>
                {% elif confirmFeedRegister %}
                    <h2 id="update">Zgłoś bloga</h2>
                {% elif contactForm %}
                    <h2 id="update">Kontakt</h2>
                {% elif newsletter or confirmNewsletterRegister %}
                    <h2 id="update">Newsletter</h2>
                {% elif "/szukaj/" in request.path %}
                    <h2 id="update">Wyszukiwarka</h2>
                {% else %}
                    {% if error == "404" or error == "500" %}
                        <h2 id="update">Wystąpił błąd</h2>
                    {% else %}
                        <h2 id="update">Ostatnia aktualizacja: {{ config.update_data }}</h2>
                    {% endif %}
                {% endif %}
            </section>
		</header>
        <section id="center">
            <section id="block">
                {% if config.newsletter %}
                    <article>
                        <h3>Newsletter</h3>
                        <p>Zapisz się do newslettera aby raz w miesiącu otrzymać podsumowanie <strong>aktualności z planety</strong> oraz <strong>oferty pracy</strong> dla programistów Python.</p>
                        <p><br>Podaj swój adres e-mail.</p>
                        <form action="/planeta/newsletter/" method="post">
                            {% csrf_token %}
                            <input type="text" id="newsletter_email" name="email" title="Wpisz adres e-mail">
                            <input id="button" type="submit" title="Zapisz się do newslettera" value="ZAPISZ SIĘ">
                            {% if newsletter.email.errors %}
                                {% for error in newsletter.email.errors %}
                                    <p>{{ error }}</p>
                                {% endfor %}
                            {% endif %}
                            <aside>
                                <input type="checkbox" name="regulation" id="id_regulation" title="Zaakceptuj regulamin">
                                <label for="id_regulation">Zaakceptuj <a href="/planeta/newsletter-regulamin" title="Newsletter regulamin">regulamin</a>.</label>
                                {% if newsletter.regulation.errors %}
                                    {% for error in newsletter.regulation.errors %}
                                        <p>{{ error }}</p>
                                    {% endfor %}
                                {% endif %}
                            </aside>
                        </form>
                    </article>
                    <aside class="space"></aside>
                {% endif %}
                {% if feeds %}
                    <article>
                        <h3>Blogerzy</h3>
                        <nav>
                            <ul>
                                {% for feed in feeds reversed %}
                                    <li>&#x2022; <a href="http://{{ feed.source }}/" title="{{ feed.author }}" rel="nofollow">{{ feed.author }}</a></li>
                                {% endfor %}
                            </ul>
                        </nav>
                    </article>
                {% endif %}
            </section>
            <section id="news">
                {% block content %}
                {% endblock %}
            </section>
        </section>
        <footer>Copyright &copy; 2013 by <a href="http://pl.python.org/" title="Polish Python Coders Group">Polish Python Coders Group</a>. Powered by <a href="https://bitbucket.org/katharsis/spreadthegospel" title="SpreadTheGospel - planet engine written in Python language and Django framework">SpreadTheGospel</a>.</footer>
        <script type="text/javascript">var _gaq=_gaq||[];_gaq.push(["_setAccount","UA-4978557-3"]);_gaq.push(["_trackPageview"]);(function(){var a=document.createElement("script");a.type="text/javascript";a.async=!0;a.src=("https:"==document.location.protocol?"https://ssl":"http://www")+".google-analytics.com/ga.js";var b=document.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b)})();</script>
	</body>
</html>
{% endspaceless %}

core/templates/index.html
{% extends "base.html" %}
    {% block content %}
        {% for post in posts %}
            {% ifchanged %}<h3>{{ post.date|date:"j F Y"|lower }}</h3>{% endifchanged %}
            <article>
                <h4><aside class="author">{{ post.author }}: </aside><a href="/planeta/{{ post.url }}" title="{{ post.title}}">{{ post.title }}</a></h4>
                {% if post.text|safe|wordcount > truncatewords %}
                    {{ post.text|safe|truncatewords_html:truncatewords }}
                    <p class="readmore"><a href="/planeta/{{ post.url }}">Czytaj więcej</a></p>
                {% else %}
                    {{ post.text|safe }}
                {% endif %}
            </article>
        {% endfor %}
        <section id="pagination">
            {% if posts.has_next %}
                <aside id="old"><a href="/planeta/news/{{ posts.next_page_number }}/" title="Starsze newsy">&larr; Starsze</a></aside>
            {% endif %}
            {% if posts.has_previous %}
                <aside id="new"><a href="/planeta/news/{{ posts.previous_page_number }}/" title="Nowsze newsy">Nowsze &rarr;</a></aside>
            {% endif %}
        </section>
    {% endblock %}

core/templates/news.html
{% extends "base.html" %}
    {% block title %}{% if post.title %}{{ post.title }} -{% endif %}{% endblock %}
    {% block content %}
        <h3>{{ post.date|date:"j F Y"|lower }}</h3>
        <article>
            <h4><aside class="author">{{ post.author }}: </aside><a href="/{{ post.url }}" title="{{ post.title}}">{{ post.title }}</a></h4>
            {{ post.text|safe }}
        </article>
    {% endblock %}

core/templates/newsletter.html
{% extends "base.html" %}
    <title>{% block title %}Newsletter -{% endblock %} pl.python.org/planeta</title>
    {% block content %}
        {% if validation %}
            <p class="sukces">Zgłoszenie zostało przyjęte.</p>
            <p class="mp">Sprawdź skrzynkę pocztową, na którą zostanie wysłana prośba o potwierdzenie zapisu. Gdyby potwierdzenie nie dotarło, skontaktuj się z nami z poziomu <a href="/planeta/kontakt" title="Formularz kontaktowy">formularza kontaktowego</a>.</p>
            <p class="mp">Wróć do <a href="/planeta" title="Strona główna">strony głównej</a>.</p>
        {% elif confirmNewsletterRegister == "yes" %}
            <p class="sukces">Dziękujemy za zapisanie się do naszego newslettera.</p>
            <p class="mp">Wróć do <a href="/planeta" title="Strona główna">strony głównej</a>.</p>
        {% elif confirmNewsletterRegister == "no" %}
            <p class="error">Twój link aktywacyjny wygasł lub podany adres e-mail znajduje się już w bazie danych.</p>
            <p class="mp">Wróć do <a href="/planeta" title="Strona główna">strony głównej</a>.</p>
        {% else %}
            <p class="error">Błędnie wypełniony formularz</p>
            <p class="mp">Wróć do <a href="/planeta" title="Strona główna">strony głównej</a>.</p>
        {% endif %}
    {% endblock %}

core/templates/subpage.html
{% extends "base.html" %}
    {% block title %}{% if site.title %}{{ site.title }} -{% endif %}{% endblock %}
    {% block content %}
        {% if confirmFeedRegister == "yes" %}
            <p class="sukces">Zgłoszenie zostało przyjęte. Dziękujemy.</p>
            <p class="mp">W trosce o naszych czytelników, każdy nowo zgłoszony blog musi przejść przez dodatkowy proces weryfikacji. Moderator dokona tych czynności tak szybko jak będzie to możliwe.</p>
            <p class="mp">Wróć do <a href="/planeta" title="Strona główna">strony głównej</a>.</p>
        {% elif confirmFeedRegister == "no" %}
            <p class="error">Wystąpił nieznany błąd.</p>
            <p class="mp">Spróbuj <a href="../" title="Zgłoś bloga">jeszcze raz</a> lub wróć do <a href="/planeta" title="Strona główna">strony głównej</a>.</p>
        {% elif confirmFeedRegister == "uniq" %}
            <p class="error">Podany adres kanału znajduje się już w bazie danych.</p>
            <p class="mp">Spróbuj <a href="../" title="Zgłoś bloga">jeszcze raz</a> lub wróć do <a href="/planeta" title="Strona główna">strony głównej</a>.</p>
        {% endif %}
        {% if contactForm == "yes" %}
            <p class="sukces">Wiadomość została wysłana. Dziękujemy.</p>
            <p class="mp">Wróć do <a href="/planeta" title="Strona główna">strony głównej</a>.</p>
        {% elif contactForm == "no" %}
            <p class="error">Wystąpił nieznany błąd.</p>
            <p class="mp">Spróbuj <a href="../" title="Zgłoś bloga">jeszcze raz</a> lub wróć do <a href="/planeta" title="Strona główna">strony głównej</a>.</p>
        {% endif %}
        {% if error == "404" or error == "500" %}
            <p class="error">Nie odnaleziono strony lub pliku.</p>
            <p class="mp">Wróć do <a href="/planeta" title="Strona główna">strony głównej</a>.</p>
        {% endif %}
        {{ site.text|safe }}
        {% if site.selectedModule == 0 %}
            <form action="{{ request.path }}" method="post">
                {% csrf_token %}
                <fieldset>
                    <label for="id_author">Imię i nazwisko/Nick</label>
                    {{ feedRegisterForm.author }}
                    {% if feedRegisterForm.author.errors %}
                        {% for error in feedRegisterForm.author.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    {% endif %}
                    <label for="id_email">E-mail</label>
                    {{ feedRegisterForm.email }}
                    {% if feedRegisterForm.email.errors %}
                        {% for error in feedRegisterForm.email.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    {% endif %}
                    <label for="id_source">RSS/ATOM</label>
                    {{ feedRegisterForm.source }}
                    {% if feedRegisterForm.source.errors %}
                        {% for error in feedRegisterForm.source.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    {% endif %}
                    <label for="id_token">Token</label>
                    <aside>
                        {{ feedRegisterForm.token }}
                        <img src="/planeta/captcha.png/subpage_{{ site.id }}" width="120" height="30" alt="Przepisz token z obrazka" title="Przepisz token z obrazka">
                    </aside>
                    {% if feedRegisterForm.token.errors %}
                        {% for error in feedRegisterForm.token.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    {% endif %}
                    {% if token_error %}
                        <p>{{ token_error }}</p>
                    {% endif %}
                    <aside>
                        {{ feedRegisterForm.regulation }}
                        <label for="id_regulation_sub">Zaakceptuj <a href="/planeta/zglos-bloga-regulamin" title="Regulamin planety">regulamin</a>.</label>
                    </aside>
                    {% if feedRegisterForm.regulation.errors %}
                        {% for error in feedRegisterForm.regulation.errors %}
                            <p class="regulation">{{ error }}</p>
                        {% endfor %}
                    {% endif %}
                    <input id="id_submit" type="submit" title="Wyślij zgłoszenie" value="Wyślij zgłoszenie">
                </fieldset>
            </form>
        {% elif site.selectedModule == 1 %}
            <form action="{{ request.path }}" method="post">
                {% csrf_token %}
                <fieldset>
                    <label for="id_author">Imię i nazwisko/Nick</label>
                    {{ contactForm.author }}
                    {% if contactForm.author.errors %}
                        {% for error in contactForm.author.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    {% endif %}
                    <label for="id_email">E-mail</label>
                    {{ contactForm.email }}
                    {% if contactForm.email.errors %}
                        {% for error in contactForm.email.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    {% endif %}
                    <label for="id_topic">Temat</label>
                    {{ contactForm.topic }}
                    {% if contactForm.topic.errors %}
                        {% for error in contactForm.topic.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    {% endif %}
                    <label for="id_message">Wiadomość</label>
                    {{ contactForm.message }}
                    {% if contactForm.message.errors %}
                        {% for error in contactForm.message.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    {% endif %}
                    <label for="id_token">Token</label>
                    <aside>
                        {{ contactForm.token }}
                        <img src="/planeta/captcha.png/subpage_{{ site.id }}" width="120" height="30" alt="Przepisz token z obrazka" title="Przepisz token z obrazka">
                    </aside>
                    {% if contactForm.token.errors %}
                        {% for error in contactForm.token.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    {% endif %}
                    {% if token_error %}
                        <p>{{ token_error }}</p>
                    {% endif %}
                    <input id="id_submit" type="submit" title="Wyślij wiadomość" value="Wyślij wiadomość">
                </fieldset>
            </form>
        {% endif %}
    {% endblock %}